version: '3.8'
services:  
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: log
    ports:
      - 3306:3306
    cap_add:
      - SYS_NICE
  adminer:
    image: adminer:4
    restart: always
    ports:
      - 8083:8080